# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
set_msg_config  -ruleid {5}  -id {[BD 41-1306]}  -suppress 
set_msg_config  -ruleid {6}  -id {[BD 41-1271]}  -suppress 
create_project -in_memory -part xc7s50csga324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/hj/sequncer_v2/sequncer_v2.cache/wt [current_project]
set_property parent.project_path /home/hj/sequncer_v2/sequncer_v2.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:arty-s7-50:part0:1.0 [current_project]
set_property ip_output_repo /home/hj/sequncer_v2/sequncer_v2.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files /home/hj/workspace/vanila_test/Debug/vanila_test.elf
add_files /home/hj/sequncer_v2/sequncer_v2.sdk/vanila_test/Debug/vanila_test.elf
set_property SCOPED_TO_REF cpu [get_files -all /home/hj/sequncer_v2/sequncer_v2.sdk/vanila_test/Debug/vanila_test.elf]
set_property SCOPED_TO_CELLS inst/microblaze_I [get_files -all /home/hj/sequncer_v2/sequncer_v2.sdk/vanila_test/Debug/vanila_test.elf]
read_verilog /home/hj/sequncer_v2/sequncer_v2.srcs/sources_1/imports/modules/io_map.svh
set_property file_type "Verilog Header" [get_files /home/hj/sequncer_v2/sequncer_v2.srcs/sources_1/imports/modules/io_map.svh]
read_verilog -library xil_defaultlib -sv {
  /home/hj/sequncer_v2/sequncer_v2.srcs/sources_1/imports/modules/bridge.sv
  /home/hj/sequncer_v2/sequncer_v2.srcs/sources_1/imports/modules/fifo.sv
  /home/hj/sequncer_v2/sequncer_v2.srcs/sources_1/new/gpi_core.sv
  /home/hj/sequncer_v2/sequncer_v2.srcs/sources_1/new/gpo_core.sv
  /home/hj/sequncer_v2/sequncer_v2.srcs/sources_1/imports/modules/mmio_controller.sv
  /home/hj/sequncer_v2/sequncer_v2.srcs/sources_1/imports/modules/mmio_sys_vanila.sv
  /home/hj/sequncer_v2/sequncer_v2.srcs/sources_1/imports/modules/register_file.sv
  /home/hj/sequncer_v2/sequncer_v2.srcs/sources_1/new/rti_core.sv
  /home/hj/sequncer_v2/sequncer_v2.srcs/sources_1/new/rto_core.sv
  /home/hj/sequncer_v2/sequncer_v2.srcs/sources_1/imports/modules/timer.sv
  /home/hj/sequncer_v2/sequncer_v2.srcs/sources_1/imports/modules/uart.sv
  /home/hj/sequncer_v2/sequncer_v2.srcs/sources_1/imports/modules/top.sv
}
read_ip -quiet /home/hj/sequncer_v2/sequncer_v2.srcs/sources_1/ip/cpu/cpu.xci
set_property used_in_implementation false [get_files -all /home/hj/sequncer_v2/sequncer_v2.srcs/sources_1/ip/cpu/bd_0/ip/ip_0/bd_3914_microblaze_I_0.xdc]
set_property used_in_implementation false [get_files -all /home/hj/sequncer_v2/sequncer_v2.srcs/sources_1/ip/cpu/bd_0/ip/ip_0/bd_3914_microblaze_I_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all /home/hj/sequncer_v2/sequncer_v2.srcs/sources_1/ip/cpu/bd_0/ip/ip_1/bd_3914_rst_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/hj/sequncer_v2/sequncer_v2.srcs/sources_1/ip/cpu/bd_0/ip/ip_1/bd_3914_rst_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/hj/sequncer_v2/sequncer_v2.srcs/sources_1/ip/cpu/bd_0/ip/ip_2/bd_3914_ilmb_0.xdc]
set_property used_in_implementation false [get_files -all /home/hj/sequncer_v2/sequncer_v2.srcs/sources_1/ip/cpu/bd_0/ip/ip_3/bd_3914_dlmb_0.xdc]
set_property used_in_implementation false [get_files -all /home/hj/sequncer_v2/sequncer_v2.srcs/sources_1/ip/cpu/bd_0/ip/ip_6/bd_3914_lmb_bram_I_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/hj/sequncer_v2/sequncer_v2.srcs/sources_1/ip/cpu/bd_0/ip/ip_7/bd_3914_iomodule_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/hj/sequncer_v2/sequncer_v2.srcs/sources_1/ip/cpu/bd_0/bd_3914_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/hj/sequncer_v2/sequncer_v2.srcs/sources_1/ip/cpu/cpu_board.xdc]
set_property used_in_implementation false [get_files -all /home/hj/sequncer_v2/sequncer_v2.srcs/sources_1/ip/cpu/cpu_ooc.xdc]

read_ip -quiet /home/hj/sequncer_v2/sequncer_v2.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xci
set_property used_in_implementation false [get_files -all /home/hj/sequncer_v2/sequncer_v2.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xdc]
set_property used_in_implementation false [get_files -all /home/hj/sequncer_v2/sequncer_v2.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/hj/sequncer_v2/sequncer_v2.srcs/constrs_1/imports/fpga/arty_s7.xdc
set_property used_in_implementation false [get_files /home/hj/sequncer_v2/sequncer_v2.srcs/constrs_1/imports/fpga/arty_s7.xdc]


synth_design -top top -part xc7s50csga324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
